// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrT6Il934ma3IZw7pfYQUAW9znN6UaJxg',
    appId: '1:1029662555024:web:a893470c492540e65b1115',
    messagingSenderId: '1029662555024',
    projectId: 'bike-online-ba245',
    authDomain: 'bike-online-ba245.firebaseapp.com',
    storageBucket: 'bike-online-ba245.appspot.com',
    measurementId: 'G-186M92W6C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkkflJyMvxTOLyEDjdWac6IHNjSM4Zqyo',
    appId: '1:1029662555024:android:33ff3a43686339615b1115',
    messagingSenderId: '1029662555024',
    projectId: 'bike-online-ba245',
    storageBucket: 'bike-online-ba245.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAznu-a4Nkli4KxWghX8hCDHzTlFFHA4og',
    appId: '1:1029662555024:ios:19a24440157e5f695b1115',
    messagingSenderId: '1029662555024',
    projectId: 'bike-online-ba245',
    storageBucket: 'bike-online-ba245.appspot.com',
    androidClientId: '1029662555024-32kamema5bngu0kjfe03a2feuvj0kbqe.apps.googleusercontent.com',
    iosClientId: '1029662555024-21e5fjfrv9qoa1kmjt91tlti92oc4e72.apps.googleusercontent.com',
    iosBundleId: 'com.example.bikeOnlineApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAznu-a4Nkli4KxWghX8hCDHzTlFFHA4og',
    appId: '1:1029662555024:ios:3f6cf1d5cc6596e95b1115',
    messagingSenderId: '1029662555024',
    projectId: 'bike-online-ba245',
    storageBucket: 'bike-online-ba245.appspot.com',
    androidClientId: '1029662555024-32kamema5bngu0kjfe03a2feuvj0kbqe.apps.googleusercontent.com',
    iosClientId: '1029662555024-49kbe0p524htanf9uc9vd2g6iq2q1rm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.bikeOnlineApplication.RunnerTests',
  );
}
